### ISSUE TITLE
Functions not working when prio=-1

### ISSUE THREAD

**Issue by BanditSan** [pablodz/pipewire_python#5]
[EasyEffects](https://github.com/wwmm/easyeffects) sets Sinks prio=-1
```bash
$ pw-cat --playback --list-targets
Available targets ("*" denotes default): 
*	41: description="HyperX 7.1 Audio Analog Stereo" prio=945
	165: description="EasyEffects Sink" prio=-1
```
all functions not working while easyeffects is enabled with error:
```python
>>> Controller().get_versiom()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.9/site-packages/pipewire_python/controller.py", line 126, in __init__
    self.load_list_targets(mode="playback", verbose=verbose)
  File "~/.local/lib/python3.9/site-packages/pipewire_python/controller.py", line 423, in load_list_targets
    self._pipewire_list_targets["list_playblack"] = _generate_dict_list_targets(
  File "~/.local/lib/python3.9/site-packages/pipewire_python/_utils.py", line 189, in _generate_dict_list_targets
    "prior": results_regex_prio[idx],
IndexError: list index out of range

```

without easyeefects all works fine
```python
>>> Controller().get_list_targets()
{'list_playblack': {'41': {'description': 'HyperX 7.1 Audio Analog Stereo', 'prior': '945'}, '_list_nodes': ['41'], '_node_default': ['41'], '_alsa_node': []}, 'list_record': {'42': {'description': 'HyperX 7.1 Audio Analog Stereo', 'prior': '1945'}, '_list_nodes': ['42'], '_node_default': ['42'], '_alsa_node': []}}
```

**Comment by pablodz** [comment]
I'll check the commands due  `pipewire_python` is handling commands with the shell output

**Comment by BanditSan** [comment]
Looked bit at the code and i think it's not shell output.

in _utils.py at line 175
```python
regex_prio = r"prio=(\d.*)"
```
\d matches unicode digit if im not wrong and `-` is not a digit

**Comment by pablodz** [comment]
I'm releasing a new version of the package

**Comment by pablodz** [comment]
Please, update to v0.0.93

**Comment by BanditSan** [comment]
This version now broken with or without easyeffects

**Comment by BanditSan** [comment]
@pablodz 
Works doing this way:
```python
regex_prio = r"prio=(-?\d.*)"
```

**Comment by pablodz** [comment]
> @pablodz
> Works doing this way:
> 
> ```python
> regex_prio = r"prio=(-?\d.*)"
> ```

okey, there's now a v0.0.94 on pypi
